apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
  namespace: kong
type: Opaque
stringData:
  KONG_PG_DATABASE: "kong"
  KONG_PG_USER: "kong"
  KONG_PG_HOST: "postgres-service.postgres.svc.cluster.local"
  KONG_PG_PASSWORD: "S3cR3t"
  KONG_PG_SSL: "on"
  KONG_PG_SSL_VERSION: "tlsv1_3"