apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: kong-dp
    app.kubernetes.io/name: kong
    enable-metrics: "true"
  name: kong-dp-kong-monitoring
  namespace: kong
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: kong-monitoring
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong-dp
    app.kubernetes.io/name: kong
  sessionAffinity: None
  type: NodePort
